Add auto_migrate_vnodes_duration to control whether the tiered storag…
cnosdb/docs pull request #114
Opened 2023-05-15 03:19 UTC by lutengda

…e function is enabled and the timing detection time

2023-05-15 03:20 UTC, lutengda commented
Merge this pr in the next package

2023-05-16 11:59 UTC, IvanGao01 approved these changes

2023-05-17 06:05 UTC, IvanGao01 requested changes
You should add the description of `auto_migrate_vnodes_duration` to https://docs.cnosdb.com/en/latest/reference/config.html

2023-06-05 02:25 UTC, lutengda commented
@bartliu827 Add meta configuration to this path
https://docs.cnosdb.com/en/latest/reference/config.html

2023-06-05 02:53 UTC, IvanGao01 approved these changes

2023-06-05 02:54 UTC, merged