Performance
cnosdb/docs pull request #121
Opened 2023-06-15 09:52 UTC by Lunmer

The new doc of performance.

2023-06-16 06:25 UTC, IvanGao01 requested changes

2023-06-16 06:25 UTC, IvanGao01 commented on docs/zh/latest/reference/performance.md
> +### 1.测试环境准备
这里应该提供 Docker 容器的资源配置吧，因为并不是在256G内存的环境下做的测试

2023-06-16 06:25 UTC, IvanGao01 commented on docs/zh/latest/reference/performance.md
> -## 测试环境
应该把docker启动命令贴上来，没有体现你是在什么样的资源限制下跑的测试

2023-06-19 10:31 UTC, IvanGao01 approved these changes

2023-06-19 10:32 UTC, merged

2023-09-13 09:45 UTC, mamun1055 commented on docs/zh/latest/reference/performance.md
MM MAMUN